openapi: 3.0.3
info:
  title: ""
  version: 0.0.0
paths:
  /printBarcode:
    post:
      operationId: printBarcode_create
      description: Request Print Barcode List
      summary: Send a list of products to sticker printer
      tags:
        - printBarcode
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BarcodePrintRequest"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/BarcodePrintRequest"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/BarcodePrintRequest"
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: ""
        "400":
          content:
            application/json:
              schema:
                type: integer
          description: ""
  /printShoppingList:
    post:
      operationId: printShoppingList_create
      description: Request Print Shopping List
      summary: Send a list of products to receipt printer
      tags:
        - printShoppingList
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ShoppingListRequest"
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/ShoppingListRequest"
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/ShoppingListRequest"
        required: true
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: ""
        "400":
          content:
            application/json:
              schema:
                type: integer
          description: ""
  /schema/:
    get:
      operationId: schema_retrieve
      description: |-
        OpenApi3 schema for this API. Format can be selected via content negotiation.

        - YAML: application/vnd.oai.openapi
        - JSON: application/vnd.oai.openapi+json
      parameters:
        - in: query
          name: format
          schema:
            type: string
            enum:
              - json
              - yaml
        - in: query
          name: lang
          schema:
            type: string
            enum:
              - af
              - ar
              - ar-dz
              - ast
              - az
              - be
              - bg
              - bn
              - br
              - bs
              - ca
              - cs
              - cy
              - da
              - de
              - dsb
              - el
              - en
              - en-au
              - en-gb
              - eo
              - es
              - es-ar
              - es-co
              - es-mx
              - es-ni
              - es-ve
              - et
              - eu
              - fa
              - fi
              - fr
              - fy
              - ga
              - gd
              - gl
              - he
              - hi
              - hr
              - hsb
              - hu
              - hy
              - ia
              - id
              - ig
              - io
              - is
              - it
              - ja
              - ka
              - kab
              - kk
              - km
              - kn
              - ko
              - ky
              - lb
              - lt
              - lv
              - mk
              - ml
              - mn
              - mr
              - ms
              - my
              - nb
              - ne
              - nl
              - nn
              - os
              - pa
              - pl
              - pt
              - pt-br
              - ro
              - ru
              - sk
              - sl
              - sq
              - sr
              - sr-latn
              - sv
              - sw
              - ta
              - te
              - tg
              - th
              - tk
              - tr
              - tt
              - udm
              - uk
              - ur
              - uz
              - vi
              - zh-hans
              - zh-hant
      tags:
        - schema
      security:
        - cookieAuth: []
        - basicAuth: []
        - {}
      responses:
        "200":
          content:
            application/vnd.oai.openapi:
              schema:
                type: object
                additionalProperties: {}
            application/yaml:
              schema:
                type: object
                additionalProperties: {}
            application/vnd.oai.openapi+json:
              schema:
                type: object
                additionalProperties: {}
            application/json:
              schema:
                type: object
                additionalProperties: {}
          description: ""
components:
  schemas:
    BarcodePrintRequest:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/ShoppingList"
      required:
        - data
    ShoppingList:
      type: object
      properties:
        list:
          type: array
          items:
            type: string
            maxLength: 20
            minLength: 3
          maxItems: 10
          minItems: 1
      required:
        - list
    ShoppingListRequest:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/ShoppingList"
      required:
        - data
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
